-- MySQL Script generated by MySQL Workbench
-- Tue Sep  5 14:09:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jeans_shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jeans_shop` ;

-- -----------------------------------------------------
-- Schema jeans_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jeans_shop` ;
USE `jeans_shop` ;

-- -----------------------------------------------------
-- Table `jeans_shop`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jeans_shop`.`user` ;

CREATE TABLE IF NOT EXISTS `jeans_shop`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(155) NOT NULL,
  `last_name` VARCHAR(155) NOT NULL,
  `birth_date` DATE NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  `adress` VARCHAR(155) NOT NULL,
  `zip_code` INT NOT NULL,
  `city` VARCHAR(155) NOT NULL,
  `password` VARCHAR(155) NOT NULL,
  `is_admin` TINYINT NOT NULL,
  `subscription_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeans_shop`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jeans_shop`.`article` ;

CREATE TABLE IF NOT EXISTS `jeans_shop`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `size` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(255) NOT NULL,
  `is_adult` TINYINT NOT NULL,
  `colour` VARCHAR(255) NULL,
  `is_favourite` TINYINT NOT NULL,
  `price` INT NOT NULL,
  `discount` INT NULL,
  `quantity_stock` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeans_shop`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jeans_shop`.`order` ;

CREATE TABLE IF NOT EXISTS `jeans_shop`.`order` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `status` VARCHAR(155) NOT NULL,
  `card_no` VARCHAR(20) NULL,
  `expiration_date` DATE NULL,
  `cvv_code` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `card_no_UNIQUE` (`card_no` ASC) VISIBLE,
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jeans_shop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeans_shop`.`order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jeans_shop`.`order_details` ;

CREATE TABLE IF NOT EXISTS `jeans_shop`.`order_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_article_has_order_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_article_has_order_article1_idx` (`article_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_article_has_order_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `jeans_shop`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `jeans_shop`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
